language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: bYsItWGpplmZVWN79fXmljp8ovsB/C+KO13EEcRPEqzkfZqlO17hQcFRLtRs27g9jT52YKOfckeBtqhZh5w1uR5FHWTpe4JXT4c2kd1zDp4mWMw9cy/ShUbjh1m8MZ0rEHL8Wapyl8wphRledvY/muQIiSCcU3YJPZuQKERZ2oI=
  app: silent-auction
  on:
    repo: BrunoChauvet/silent-auction
